// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUEPy3uHTpFcdNLUI7ii_iZSvkMgGIyEU',
    appId: '1:141137172814:web:6a13a55a3add15bd90a61f',
    messagingSenderId: '141137172814',
    projectId: 'loyalty-first',
    authDomain: 'loyalty-first.firebaseapp.com',
    storageBucket: 'loyalty-first.firebasestorage.app',
    measurementId: 'G-NDVXGYZKD8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCPtZ6lxHIAG2a-rocB9G-uRjrPSWO98',
    appId: '1:141137172814:ios:cd448d68074ab70190a61f',
    messagingSenderId: '141137172814',
    projectId: 'loyalty-first',
    storageBucket: 'loyalty-first.firebasestorage.app',
    iosBundleId: 'com.bunkloyalty.bunkLoyalty',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCPtZ6lxHIAG2a-rocB9G-uRjrPSWO98',
    appId: '1:141137172814:ios:cd448d68074ab70190a61f',
    messagingSenderId: '141137172814',
    projectId: 'loyalty-first',
    storageBucket: 'loyalty-first.firebasestorage.app',
    iosBundleId: 'com.bunkloyalty.bunkLoyalty',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA93kmXmnmIQugFw9iRqTub_knp7E-3wxk',
    appId: '1:141137172814:android:fddb2060a32f656790a61f',
    messagingSenderId: '141137172814',
    projectId: 'loyalty-first',
    storageBucket: 'loyalty-first.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUEPy3uHTpFcdNLUI7ii_iZSvkMgGIyEU',
    appId: '1:141137172814:web:7cf58703bee9c80c90a61f',
    messagingSenderId: '141137172814',
    projectId: 'loyalty-first',
    authDomain: 'loyalty-first.firebaseapp.com',
    storageBucket: 'loyalty-first.firebasestorage.app',
    measurementId: 'G-QTGS9CQT1T',
  );

}